if(NOT SDL2_FIND_VERSION)
	set(SDL2_FIND_VERSION 2.0.14)
endif()

set(SDL2_TARGET mingw)
set(SDL2_ARCHIVE_SUFFIX .tar.gz)
set(SDL2_ARCHIVE_FILE_NAME "SDL2-devel-${SDL2_FIND_VERSION}-${SDL2_TARGET}${SDL2_ARCHIVE_SUFFIX}")

if(NOT EXISTS "${CMAKE_CURRENT_BINARY_DIR}/sdl2/${SDL2_ARCHIVE_FILE_NAME}")
	file(
			DOWNLOAD
			"https://www.libsdl.org/release/${SDL2_ARCHIVE_FILE_NAME}"
			"${CMAKE_CURRENT_BINARY_DIR}/sdl2/${SDL2_ARCHIVE_FILE_NAME}"
			SHOW_PROGRESS
	)
endif()

set(SDL2_ARCHIVE_DIR "${CMAKE_CURRENT_BINARY_DIR}/sdl2/SDL2-devel-${SDL2_FIND_VERSION}-${SDL2_TARGET}")

file(MAKE_DIRECTORY "${SDL2_ARCHIVE_DIR}")
execute_process(
		COMMAND ${CMAKE_COMMAND} -E tar xzf "${CMAKE_CURRENT_BINARY_DIR}/sdl2/${SDL2_ARCHIVE_FILE_NAME}"
		WORKING_DIRECTORY "${SDL2_ARCHIVE_DIR}"
)

#if("${CMAKE_HOST_SYSTEM_PROCESSOR}" EQUAL "AMD64")
#	set(SDL2_DIR "${SDL2_ARCHIVE_DIR}/SDL2-${SDL2_FIND_VERSION}/x86_64-w64-mingw32")
#else()
	set(SDL2_DIR "${SDL2_ARCHIVE_DIR}/SDL2-${SDL2_FIND_VERSION}/i686-w64-mingw32")
#endif()

set(SDL2_INCLUDE_DIRS "${SDL2_DIR}/include")
#set(SDL2_SHARED_LIBRARIES "${SDL2_DIR}/bin/SDL2.dll")
set(
		SDL2_LIBRARIES mingw32
		"${SDL2_DIR}/lib/libSDL2main.a" "${SDL2_DIR}/lib/libSDL2.a"
		dinput8 dxguid dxerr8 user32 gdi32 winmm imm32 ole32 oleaut32 shell32 setupapi version uuid
)

foreach(SDL2_SHARED_LIBRARY ${SDL2_SHARED_LIBRARIES})
	get_filename_component(SDL2_SHARED_LIBRARY_FILENAME ${SDL2_SHARED_LIBRARY} NAME)
	get_filename_component(SDL2_SHARED_LIBRARY_PATH "${CMAKE_CURRENT_BINARY_DIR}/${SDL2_SHARED_LIBRARY_FILENAME}" ABSOLUTE)
	add_custom_target(
			"${SDL2_SHARED_LIBRARY_FILENAME}"
			COMMAND ${CMAKE_COMMAND} -E copy_if_different "${SDL2_SHARED_LIBRARY}" "${SDL2_SHARED_LIBRARY_PATH}"
			BYPRODUCTS "${SDL2_SHARED_LIBRARY_PATH}"
	)
	list(APPEND SDL2_LIBRARIES "${SDL2_SHARED_LIBRARY_FILENAME}")
endforeach()

add_library(SDL2::SDL2 INTERFACE IMPORTED)
target_compile_definitions(SDL2::SDL2 INTERFACE -Dmain=SDL_main)
target_include_directories(SDL2::SDL2 INTERFACE ${SDL2_INCLUDE_DIRS})
target_link_directories(SDL2::SDL2 INTERFACE ${CMAKE_CURRENT_BINARY_DIR})
target_link_libraries(SDL2::SDL2 INTERFACE ${SDL2_LIBRARIES})
